name: "transition_matrix"

train_dataset:
  _target_: datasets.dynamical_systems.TransitionMatrix
  dim: 3
  x_dim: 90
  y_dim: 90
  n_tasks: 10000
  n_samples: 1000
  dt: 0.01
  noise: 0.0
  shuffle_samples: True
val_dataset:
  _target_: ${dataset.train_dataset._target_}
  dim: ${dataset.train_dataset.dim}
  x_dim: ${dataset.train_dataset.x_dim}
  y_dim: ${dataset.train_dataset.y_dim}
  n_tasks: 1000
  n_samples: ${dataset.train_dataset.n_samples}
  dt: ${dataset.train_dataset.dt}
  noise: ${dataset.train_dataset.noise}
  shuffle_samples: ${dataset.train_dataset.shuffle_samples}
