name: "arc_symbolic_2d"

train_dataset:
  _target_: datasets.symbolic.ARCSymbolic2D
  x_dim: 6
  y_dim: 360
  n_colors: 10
  n_tasks: 10000
  n_samples: 1000
  has_ood: False
  ood_style: "random"
  shuffle_samples: True
val_dataset:
  _target_: datasets.symbolic.ARCSymbolic2D
  x_dim: ${dataset.train_dataset.x_dim}
  y_dim: ${dataset.train_dataset.y_dim}
  n_tasks: 100
  n_samples: ${dataset.train_dataset.n_samples}
  n_colors: ${dataset.train_dataset.n_colors}
  has_ood: ${dataset.train_dataset.has_ood}
  ood_style: ${dataset.train_dataset.ood_style}
  shuffle_samples: ${dataset.train_dataset.shuffle_samples}
