name: "hmm"

train_dataset:
  _target_: datasets.symbolic.HMM
  data_path: "/home/mila/e/eric.elmoznino/scratch/prequential_icl/data/hmm/train.pt"
val_dataset:
  _target_: datasets.symbolic.HMM
  data_path: "/home/mila/e/eric.elmoznino/scratch/prequential_icl/data/hmm/val.pt"
