#@package _global_

defaults:
  - predictor: MLPConcatPredictor
  - context_aggregator: Transfoptimizer
  - _self_


task_name: "meta_optimizer"

datamodule:
  _target_: datasets.interfaces.ICLDataModule
  batch_size: 256
  train_dataset: ${dataset.train_dataset}
  val_dataset: ${dataset.val_dataset}

trainer:
  max_epochs: 50

callbacks:

task:
  _target_: tasks.meta_optimizer_symbolic.MetaOptimizerForSymbolic2D
  meta_objective: prequential
  min_train_samples: 1
  lr: 1e-4
  context_aggregator: ${context_aggregator}
  predictor: ${predictor}
