#@package _global_

defaults:
  - predictor: null
  - _self_

task_name: "meta_optimizer_implicit"

datamodule:
  _target_: datasets.interfaces.ICLDataModule
  batch_size: 256
  train_dataset: ${dataset.train_dataset}
  val_dataset: ${dataset.val_dataset}

trainer:
  max_epochs: 50

callbacks:

task:
  _target_: tasks.meta_optimizer_regression.MetaOptimizerImplicitForRegression
  min_train_samples: 1
  lr: 1e-4
  model:
    _target_: models.implicit.DecoderTransformer
    x_dim: ${dataset.train_dataset.x_dim}
    y_dim: ${dataset.train_dataset.y_dim}
    h_dim: 256
    n_layers: 4
    n_heads: 4
