defaults:
  - hydra: default
  - dataset: null
  - task: null
  - task/context_aggregator: null
  - task/predictor: null
  - _self_

save_dir: "logs/"
seed: 27

logger:
  _target_: utils.logger.BufferedLogger
  entity: "dhanya-shridar"
  project: "Prequential-ICL"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  flush_every_n_steps: ${ast_eval:'${datamodule.dataset.train_dataset.n_tasks} // ${datamodule.batch_size}'}
  offline: False
  tags: null


name: ${task_name}_${dataset.name}
