defaults:
  - _self_
  - hydra: default
  - experiment: null

save_dir: "logs/"
seed: 27

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  entity: "dhanya-shridar"
  project: "Prequential-ICL"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null
