defaults:
  - _self_
  - hydra: default
  - experiment: null
  - z_dim: 512 # Dimension of the latent space

save_dir: "logs/"
seed: 27

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  entity: null
  project: "Prequential-ICL"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null

transfoptimizer:
  _target_: models.context_aggregator.Transfoptimizer
  z_dim: ${defaults.z_dim}
  h_dim: 512
  n_layers: 8
  n_heads: 4
  mlp_dim: 512
  layer_norm_eps: 1e-5
  dropout: 0.0

vanilla_predictor:
  _target_: models.predictor.MLPConcatPredictor
  h_dim: 512
  z_dim: ${defaults.z_dim}
  n_layers: 2
