defaults:
  - _self_
  - hydra: default
  - experiment: null

save_dir: "logs/"
seed: 27

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  entity: null
  project: "Prequential-ICL"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null


model:
    _target_: models.context_aggregator.Transfoptimizer
    n_heads: 4
    n_hidden: 512
    n_layers: 8
    layer_norm_eps: 1e-5
    _target_: models.predictor.VanillaPredictor
    n_hidden: 512
    n_layers: 2
