_target_: models.context_aggregator.Mambaoptimizer
x_dim: ${ast_eval:'${dataset.train_dataset.x_dim} + ${dataset.train_dataset.y_dim}'}
z_dim: 128
h_dim: 256
n_layers: 4
mixer_type: "Mamba1"
mixer_config:
  d_state: 8
  d_conv: 4