_target_: models.context_aggregator.VTOptimizer
x_dim: ${ast_eval:'${task.context_aggregator.feature_map.out_channels}*2'}
z_dim: 128
h_dim: 256
n_layers: 4
n_heads: 4
feature_map:
  _target_: models.utils.CNNModule
  in_channels: ${datamodule.train_dataset.n_colors}
  out_channels: 64
  stride: 1
